# Generated by Django 2.2.12 on 2022-08-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=10, verbose_name='作者')),
                ('Country', models.CharField(max_length=10, verbose_name='国家')),
            ],
            options={
                'verbose_name_plural': '作者信息',
                'db_table': '作者信息',
            },
        ),
        migrations.CreateModel(
            name='PublisherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publisher', models.CharField(max_length=10, verbose_name='出版社')),
            ],
            options={
                'verbose_name_plural': '出版社信息',
                'db_table': '出版社信息',
            },
        ),
        migrations.CreateModel(
            name='ThemeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme', models.CharField(max_length=10, verbose_name='主题/题材')),
            ],
            options={
                'verbose_name_plural': '主题/题材信息',
                'db_table': '主题/题材信息',
            },
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=30, unique=True, verbose_name='书名')),
                ('Reading', models.CharField(default='未读', max_length=10, verbose_name='阅读情况')),
                ('Price', models.DecimalField(decimal_places=2, default='7.21', max_digits=5, verbose_name='购入价格')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyLibrary.AuthorInfo', verbose_name='作者')),
                ('Publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyLibrary.PublisherInfo', verbose_name='出版社')),
                ('Theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyLibrary.ThemeInfo', verbose_name='主题/题材')),
            ],
            options={
                'verbose_name_plural': '图书基本信息',
                'db_table': '图书基本信息',
            },
        ),
    ]
