# Generated by Django 2.2.12 on 2022-08-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='Price',
            field=models.DecimalField(decimal_places=2, default='721', max_digits=5, verbose_name='购入价格'),
        ),
    ]
